(lang dune 3.20)

(name bench_httpcats_flambda)

(package
 (name bench_httpcats_flambda)
 (allow_empty)
 (synopsis "Hello-world benchmark server: httpcats (Flambda)")
 (depends
  (ocaml
   (= 5.5.0))
  ocaml-option-flambda
  httpcats
  h1
  (miou
   (>= 0.3.0))))
