(lang dune 3.20)

(name bench_dream_flambda)

(package
 (name bench_dream_flambda)
 (allow_empty)
 (synopsis "Hello-world benchmark server: Dream (Flambda)")
 (depends
  (ocaml
   (= 5.5.0))
  ocaml-option-flambda
  (dream
   (>= 1.0.0~alpha7))))
