(lang dune 3.24)

(name bench_tiny_httpd_moonpool)

(package
 (name bench_tiny_httpd_moonpool)
 (allow_empty)
 (synopsis "Hello-world benchmark server: tiny_httpd on Moonpool")
 (depends
  (ocaml
   (= 5.5.0))
  (moonpool
   (>= 0.9))
  (tiny_httpd
   (>= 0.21))))
