(lang dune 3.20)

(name bench_vif_multicore)

(package
 (name bench_vif_multicore)
 (allow_empty)
 (synopsis "Hello-world benchmark server: Vif (multicore)")
 (depends
  (ocaml
   (= 5.5.0))
  (vif
   (= 0.0.1~beta4))))
