(lang dune 3.20)

(name bench_httpun_eio_multicore)

(package
 (name bench_httpun_eio_multicore)
 (allow_empty)
 (synopsis "Hello-world benchmark server: httpun Eio (multicore)")
 (depends
  (ocaml
   (= 5.5.0))
  (httpun
   (>= 0.2.0))
  (httpun-eio
   (>= 0.2.0))
  (gluten
   (>= 0.5.0))
  (eio
   (>= 1.1))
  (eio_main
   (>= 1.1))))
