(lang dune 3.24)

(name bench_cohttp_eio_flambda)

(package
 (name bench_cohttp_eio_flambda)
 (allow_empty)
 (synopsis "Hello-world benchmark server: Cohttp Eio (Flambda)")
 (depends
  (ocaml
   (= 5.5.0))
  ocaml-option-flambda
  (cohttp-eio
   (>= 6.2.2))
  (eio_main
   (>= 1.1))))
